export const seededTickerEvents = [
  { username: "shadowfox", game: "Reaction Duel", amount: 100 },
  { username: "kira_06", game: "Chess", amount: 200 },
  { username: "nova_xx", game: "Memory Match", amount: 100 },
  { username: "drift99", game: "Connect 4", amount: 50 },
  { username: "alex_p", game: "Spelling Bee", amount: 100 },
  { username: "silent_k", game: "Checkers", amount: 200 },
  { username: "phoenix77", game: "Chess", amount: 500 },
  { username: "maverick", game: "Reaction Duel", amount: 100 },
  { username: "echo_99", game: "Typing Race", amount: 100 },
  { username: "vortex", game: "Trivia", amount: 200 },
  { username: "lunar_op", game: "Chess", amount: 100 },
  { username: "rogue_z", game: "Memory Match", amount: 50 },
];

export const fallbackFeaturedMatches = [
  {
    player1: { username: "phoenix77", rank: "GOLD II" },
    player2: { username: "shadowfox", rank: "GOLD I" },
    game: "Chess",
    bet: 500,
  },
  {
    player1: { username: "AX", rank: "PLATINUM I" },
    player2: { username: "kira_06", rank: "GOLD III" },
    game: "Chess",
    bet: 750,
  },
  {
    player1: { username: "nova_xx", rank: "DIAMOND" },
    player2: { username: "drift99", rank: "PLATINUM II" },
    game: "Chess",
    bet: 1000,
  },
];

// The Immortal Game — Adolf Anderssen vs Lionel Kieseritzky, London 1851
// One of the most famous chess games ever played. 23 moves ending in a brilliant checkmate.
// We store moves in a simplified format: starting square, ending square, and the piece glyph.
export const fabricatedMoveSequence = [
  { from: "e2", to: "e4", piece: "♙" },
  { from: "e7", to: "e5", piece: "♟" },
  { from: "f2", to: "f4", piece: "♙" },
  { from: "e5", to: "f4", piece: "♟" },
  { from: "f1", to: "c4", piece: "♗" },
  { from: "d8", to: "h4", piece: "♛" },
  { from: "e1", to: "f1", piece: "♔" },
  { from: "b7", to: "b5", piece: "♟" },
  { from: "c4", to: "b5", piece: "♗" },
  { from: "g8", to: "f6", piece: "♞" },
  { from: "g1", to: "f3", piece: "♘" },
  { from: "h4", to: "h6", piece: "♛" },
  { from: "d2", to: "d3", piece: "♙" },
  { from: "f6", to: "h5", piece: "♞" },
  { from: "f3", to: "h4", piece: "♘" },
  { from: "h6", to: "g5", piece: "♛" },
  { from: "h4", to: "f5", piece: "♘" },
  { from: "c7", to: "c6", piece: "♟" },
  { from: "g2", to: "g4", piece: "♙" },
  { from: "h5", to: "f6", piece: "♞" },
  { from: "h1", to: "g1", piece: "♖" },
  { from: "c6", to: "b5", piece: "♟" },
  { from: "h2", to: "h4", piece: "♙" },
  { from: "g5", to: "g6", piece: "♛" },
  { from: "h4", to: "h5", piece: "♙" },
  { from: "g6", to: "g5", piece: "♛" },
  { from: "d1", to: "f3", piece: "♕" },
  { from: "f6", to: "g8", piece: "♞" },
  { from: "c1", to: "f4", piece: "♗" },
  { from: "g5", to: "f6", piece: "♛" },
  { from: "b1", to: "c3", piece: "♘" },
  { from: "f8", to: "c5", piece: "♝" },
  { from: "c3", to: "d5", piece: "♘" },
  { from: "f6", to: "b2", piece: "♛" },
  { from: "f4", to: "d6", piece: "♗" },
  { from: "c5", to: "g1", piece: "♝" },
  { from: "e4", to: "e5", piece: "♙" },
  { from: "b2", to: "a1", piece: "♛" },
  { from: "f1", to: "e2", piece: "♔" },
  { from: "b8", to: "a6", piece: "♞" },
  { from: "f5", to: "g7", piece: "♘" },
  { from: "e8", to: "d8", piece: "♚" },
  { from: "f3", to: "f6", piece: "♕" },
];
