/**
 * Spelling Bee word database. All spellings and definitions verified.
 * Words are organized by difficulty for round progression.
 */

export type SpellingDifficulty = "easy" | "medium" | "hard" | "expert";

export interface SpellingWord {
  word: string;
  definition: string;
  difficulty: SpellingDifficulty;
  /** Example sentence for "Use in sentence" (read aloud) */
  sentence?: string;
  hint?: string;
  origin?: string;
  /** Optional common misspellings for bot/validation hints */
  commonMisspellings?: string[];
}

export const SPELLING_WORDS: SpellingWord[] = [
  // --- EASY (50+) ---
  { word: "necessary", definition: "Required or essential", difficulty: "easy", hint: "One 'c', two 's'", origin: "Latin", commonMisspellings: ["neccessary", "necesary"], sentence: "It is necessary to finish the form." },
  { word: "separate", definition: "To divide or keep apart", difficulty: "easy", hint: "Often confused with 'desperate'", origin: "Latin", commonMisspellings: ["seperate"], sentence: "Please separate the eggs from the yolks." },
  { word: "definitely", definition: "Without any doubt; certainly", difficulty: "easy", hint: "Contains 'finite'", origin: "Latin", commonMisspellings: ["definately", "definatly"], sentence: "I will definitely be there." },
  { word: "occurrence", definition: "An event or incident", difficulty: "easy", hint: "Double c, double r", origin: "Latin", commonMisspellings: ["occurence", "occurance"], sentence: "Such an occurrence is rare." },
  { word: "believe", definition: "To accept as true", difficulty: "easy", hint: "i before e", origin: "Old English", commonMisspellings: ["beleive"], sentence: "I believe you are right." },
  { word: "calendar", definition: "A system for organizing days and months", difficulty: "easy", hint: "Not 'calender'", origin: "Latin", commonMisspellings: ["calender"], sentence: "Check the calendar for the date." },
  { word: "environment", definition: "The surroundings or conditions in which one lives", difficulty: "easy", origin: "French", sentence: "We must protect the environment." },
  { word: "beginning", definition: "The start or first part of something", difficulty: "easy", hint: "Double n", origin: "Old English", commonMisspellings: ["begining"], sentence: "From the beginning, she was a natural." },
  { word: "argument", definition: "A disagreement or debate between people", difficulty: "easy", hint: "No 'e' after 'argu'", origin: "Latin", commonMisspellings: ["arguement"], sentence: "They had an argument about the rules." },
  { word: "experience", definition: "Knowledge gained through involvement in events", difficulty: "easy", origin: "Latin", sentence: "Experience is the best teacher." },
  { word: "government", definition: "The system by which a country is ruled", difficulty: "easy", hint: "Govern + ment", origin: "Latin", sentence: "The government announced a new policy." },
  { word: "different", definition: "Not the same as another", difficulty: "easy", commonMisspellings: ["diferent", "diffrent"], sentence: "Everyone is different in their own way." },
  { word: "restaurant", definition: "A place where meals are served to customers", difficulty: "easy", origin: "French", commonMisspellings: ["restaraunt", "resturant"], sentence: "We had dinner at a fine restaurant." },
  { word: "temperature", definition: "The degree of heat or cold", difficulty: "easy", origin: "Latin", sentence: "The temperature dropped overnight." },
  { word: "immediately", definition: "At once; without delay", difficulty: "easy", hint: "Immediate + ly", commonMisspellings: ["imediately", "immediatly"], sentence: "Please respond immediately." },
  { word: "appreciate", definition: "To recognize the value of something", difficulty: "easy", origin: "Latin" },
  { word: "committee", definition: "A group appointed for a specific function", difficulty: "easy", hint: "Double m, double t, double e", commonMisspellings: ["comittee", "commitee"] },
  { word: "guarantee", definition: "A promise or assurance", difficulty: "easy", origin: "French", commonMisspellings: ["garantee", "garanty"] },
  { word: "independent", definition: "Free from outside control", difficulty: "easy", hint: "Ends in -ent", commonMisspellings: ["independant"] },
  { word: "knowledge", definition: "Information and skills acquired through experience", difficulty: "easy", hint: "Silent 'd'", origin: "Old English", commonMisspellings: ["knowlege"] },
  { word: "library", definition: "A building or room containing collections of books", difficulty: "easy", commonMisspellings: ["libary", "libary"] },
  { word: "millennium", definition: "A period of one thousand years", difficulty: "easy", hint: "Double l, double n", origin: "Latin", commonMisspellings: ["milennium", "millenium"] },
  { word: "neighbor", definition: "A person living near or next to another", difficulty: "easy", origin: "Old English", commonMisspellings: ["neighbour"] },
  { word: "occasion", definition: "A particular time or instance of an event", difficulty: "easy", hint: "Double c, one s", commonMisspellings: ["occassion"] },
  { word: "parallel", definition: "Side by side and having the same distance apart", difficulty: "easy", hint: "Double l twice", commonMisspellings: ["parrallel", "paralel"] },
  { word: "privilege", definition: "A special right or advantage", difficulty: "easy", origin: "Latin", commonMisspellings: ["priviledge"] },
  { word: "profession", definition: "A paid occupation requiring training", difficulty: "easy", origin: "Latin" },
  { word: "recommend", definition: "To suggest as being good or suitable", difficulty: "easy", hint: "One c, two m", commonMisspellings: ["reccommend", "recomend"] },
  { word: "schedule", definition: "A plan for carrying out activities", difficulty: "easy", origin: "Greek", commonMisspellings: ["schedual"] },
  { word: "surprise", definition: "An unexpected event or occurrence", difficulty: "easy", commonMisspellings: ["suprise", "surprize"] },
  { word: "receive", definition: "To be given or presented with something", difficulty: "easy", hint: "i before e except after c", origin: "Latin", commonMisspellings: ["recieve"] },
  { word: "achieve", definition: "To successfully reach a goal", difficulty: "easy", hint: "i before e", commonMisspellings: ["acheive"] },
  { word: "because", definition: "For the reason that", difficulty: "easy", commonMisspellings: ["becuase", "becasue"] },
  { word: "beautiful", definition: "Pleasing to the senses or mind", difficulty: "easy", commonMisspellings: ["beatiful", "beutiful"] },
  { word: "business", definition: "A person's regular occupation or trade", difficulty: "easy", commonMisspellings: ["buisness", "busness"] },
  { word: "column", definition: "An upright pillar supporting a structure", difficulty: "easy", hint: "Silent 'n'", origin: "Latin", commonMisspellings: ["colum"] },
  { word: "conscience", definition: "An inner feeling of right and wrong", difficulty: "easy", hint: "Science in the middle", commonMisspellings: ["concience"] },
  { word: "conscious", definition: "Aware of and responding to one's surroundings", difficulty: "easy", commonMisspellings: ["concious", "consious"] },
  { word: "embarrass", definition: "To cause someone to feel self-conscious", difficulty: "easy", hint: "Double r, double s", commonMisspellings: ["embarass", "embaress"] },
  { word: "existence", definition: "The fact or state of living or being", difficulty: "easy", origin: "Latin" },
  { word: "familiar", definition: "Well known from long association", difficulty: "easy", commonMisspellings: ["familar", "familliar"] },
  { word: "February", definition: "The second month of the year", difficulty: "easy", hint: "First r is often dropped in speech", commonMisspellings: ["Febuary", "Febuary"] },
  { word: "foreign", definition: "Of, from, or characteristic of another country", difficulty: "easy", hint: "Weird 'eig'", commonMisspellings: ["foriegn", "forign"] },
  { word: "friend", definition: "A person whom one knows and has a bond of mutual affection", difficulty: "easy", commonMisspellings: ["freind", "frend"] },
  { word: "height", definition: "The measurement from base to top", difficulty: "easy", hint: "Ends in -eighth sound", commonMisspellings: ["hieght", "heigth"] },
  { word: "humorous", definition: "Causing laughter; comic", difficulty: "easy", commonMisspellings: ["humourous"] },
  { word: "interrupt", definition: "To stop the continuous progress of", difficulty: "easy", hint: "Double r", commonMisspellings: ["interupt"] },
  { word: "judgment", definition: "The ability to make considered decisions", difficulty: "easy", commonMisspellings: ["judgement"] },
  { word: "leisure", definition: "Free time when one is not working", difficulty: "easy", origin: "French", commonMisspellings: ["liesure"] },
  { word: "license", definition: "A permit from an authority to do something", difficulty: "easy", commonMisspellings: ["licence"] },
  { word: "medicine", definition: "A substance used to treat disease", difficulty: "easy", origin: "Latin" },
  { word: "minute", definition: "A period of sixty seconds", difficulty: "easy", origin: "Latin" },
  { word: "nuclear", definition: "Relating to the nucleus of an atom", difficulty: "easy", commonMisspellings: ["nucular"] },
  { word: "occur", definition: "To happen; take place", difficulty: "easy", hint: "Double c", commonMisspellings: ["occure"] },
  { word: "opportunity", definition: "A set of circumstances making something possible", difficulty: "easy", commonMisspellings: ["oppertunity"] },
  { word: "particular", definition: "Used to single out an individual member of a group", difficulty: "easy", commonMisspellings: ["particular"] },
  { word: "personnel", definition: "People employed in an organization", difficulty: "easy", origin: "French", commonMisspellings: ["personel"] },
  { word: "possess", definition: "To have as belonging to one", difficulty: "easy", hint: "Double s twice", commonMisspellings: ["posess", "posses"] },
  { word: "publicly", definition: "In a way that is open to or observable by the public", difficulty: "easy", commonMisspellings: ["publically"] },
  { word: "really", definition: "In actual fact; as opposed to what is said or imagined", difficulty: "easy", commonMisspellings: ["realy"] },
  { word: "referred", definition: "Past tense of refer", difficulty: "easy", hint: "Double r when adding -ed", commonMisspellings: ["refered"] },
  { word: "relevant", definition: "Closely connected or appropriate", difficulty: "easy", commonMisspellings: ["relevent"] },
  { word: "religious", definition: "Relating to or believing in a religion", difficulty: "easy", commonMisspellings: ["religous"] },
  { word: "tomorrow", definition: "The day after today", difficulty: "easy", commonMisspellings: ["tommorow", "tommorrow"] },
  { word: "truly", definition: "In a truthful way", difficulty: "easy", commonMisspellings: ["truely"] },
  { word: "until", definition: "Up to the point in time mentioned", difficulty: "easy", commonMisspellings: ["untill"] },
  { word: "weird", definition: "Suggesting something supernatural", difficulty: "easy", hint: "i before e exception", commonMisspellings: ["wierd"], sentence: "That was a weird dream." },
  { word: "writing", definition: "The activity of composing text", difficulty: "easy", commonMisspellings: ["writting"], sentence: "Writing well takes practice." },

  // --- MORE EASY (with sentences for audio) ---
  { word: "absence", definition: "The state of being away from a place", difficulty: "easy", origin: "Latin", sentence: "Her absence from the meeting was noticed.", commonMisspellings: ["absense"] },
  { word: "acceptable", definition: "Able to be agreed on; suitable", difficulty: "easy", sentence: "The proposal was acceptable to everyone.", commonMisspellings: ["acceptible"] },
  { word: "accidentally", definition: "By chance; unintentionally", difficulty: "easy", sentence: "I accidentally deleted the file.", commonMisspellings: ["accidently"] },
  { word: "acquire", definition: "To gain possession of something", difficulty: "easy", origin: "Latin", sentence: "The company plans to acquire a competitor.", commonMisspellings: ["aquire"] },
  { word: "adequate", definition: "Sufficient for a specific need", difficulty: "easy", origin: "Latin", sentence: "The supplies were adequate for the trip.", commonMisspellings: ["adequit"] },
  { word: "amateur", definition: "A person who engages in an activity without pay", difficulty: "easy", origin: "French", sentence: "He competed as an amateur boxer.", commonMisspellings: ["amature"] },
  { word: "apparent", definition: "Clearly visible or understood", difficulty: "easy", sentence: "The solution was apparent to everyone.", commonMisspellings: ["aparent"] },
  { word: "awkward", definition: "Causing difficulty; hard to deal with", difficulty: "easy", sentence: "There was an awkward silence in the room.", commonMisspellings: ["akward"] },
  { word: "bargain", definition: "An agreement between parties on a deal", difficulty: "easy", sentence: "She found a great bargain at the sale.", commonMisspellings: ["bargan"] },
  { word: "boundary", definition: "A line that marks the limits of an area", difficulty: "easy", sentence: "The fence marks the property boundary.", commonMisspellings: ["boundry"] },
  { word: "brilliant", definition: "Exceptionally clever or talented", difficulty: "easy", sentence: "She had a brilliant idea for the project.", commonMisspellings: ["briliant"] },
  { word: "campaign", definition: "An organized effort to achieve a goal", difficulty: "easy", origin: "Latin", sentence: "The election campaign lasted six months.", commonMisspellings: ["campain"] },
  { word: "category", definition: "A class or division of things", difficulty: "easy", sentence: "This falls into the luxury category.", commonMisspellings: ["catagory"] },
  { word: "ceremony", definition: "A formal event performed on special occasions", difficulty: "easy", sentence: "The wedding ceremony was beautiful.", commonMisspellings: ["ceremoney"] },
  { word: "challenge", definition: "A task or situation that tests abilities", difficulty: "easy", sentence: "Climbing the mountain was a real challenge.", commonMisspellings: ["chalenge"] },
  { word: "colleague", definition: "A person with whom one works", difficulty: "easy", sentence: "My colleague helped me finish the report.", commonMisspellings: ["collegue"] },
  { word: "commercial", definition: "Related to or engaged in commerce", difficulty: "easy", sentence: "The commercial district was busy.", commonMisspellings: ["comercial"] },
  { word: "communicate", definition: "To share or exchange information", difficulty: "easy", sentence: "We need to communicate more effectively.", commonMisspellings: ["comunicate"] },
  { word: "community", definition: "A group of people living in the same area", difficulty: "easy", sentence: "The community organized a festival.", commonMisspellings: ["comunity"] },
  { word: "comparison", definition: "The act of examining similarities and differences", difficulty: "easy", sentence: "The comparison revealed key differences.", commonMisspellings: ["comparrison"] },
  { word: "competition", definition: "The activity of competing against others", difficulty: "easy", sentence: "The competition was fierce this year.", commonMisspellings: ["competion"] },
  { word: "completely", definition: "Totally; utterly", difficulty: "easy", sentence: "The project is completely finished.", commonMisspellings: ["completly"] },
  { word: "concentrate", definition: "To focus attention or effort", difficulty: "easy", sentence: "Please concentrate on the task at hand.", commonMisspellings: ["concentraite"] },
  { word: "confident", definition: "Feeling sure of oneself", difficulty: "easy", sentence: "She was confident about the presentation.", commonMisspellings: ["confidant"] },
  { word: "confusion", definition: "A state of being bewildered", difficulty: "easy", sentence: "There was confusion about the schedule.", commonMisspellings: ["confussion"] },
  { word: "connection", definition: "A relationship or link between things", difficulty: "easy", sentence: "The connection between the two events was clear.", commonMisspellings: ["conection"] },
  { word: "consequence", definition: "A result or effect of an action", difficulty: "easy", sentence: "Losing was a consequence of poor preparation.", commonMisspellings: ["consequense"] },
  { word: "considerable", definition: "Notably large in size or amount", difficulty: "easy", sentence: "There was a considerable improvement.", commonMisspellings: ["considerible"] },
  { word: "consistent", definition: "Acting the same way over time", difficulty: "easy", sentence: "Her performance has been consistent all year.", commonMisspellings: ["consistant"] },
  { word: "continuous", definition: "Forming an unbroken whole", difficulty: "easy", sentence: "The continuous rain lasted three days.", commonMisspellings: ["continous"] },
  { word: "convenience", definition: "The state of being useful or easy", difficulty: "easy", sentence: "The store is open for your convenience.", commonMisspellings: ["convinience"] },
  { word: "criticism", definition: "The expression of disapproval", difficulty: "easy", sentence: "The criticism was harsh but fair.", commonMisspellings: ["criticisim"] },
  { word: "curiosity", definition: "A strong desire to know something", difficulty: "easy", sentence: "Her curiosity led her to investigate.", commonMisspellings: ["curiousity"] },
  { word: "deceive", definition: "To cause someone to believe something false", difficulty: "easy", sentence: "He tried to deceive the audience.", commonMisspellings: ["decieve"] },
  { word: "decision", definition: "A conclusion reached after consideration", difficulty: "easy", sentence: "Making the decision was difficult.", commonMisspellings: ["decicion"] },
  { word: "desperate", definition: "Feeling hopeless or having great need", difficulty: "easy", sentence: "They were desperate for water.", commonMisspellings: ["desparate"] },
  { word: "determine", definition: "To cause to occur in a particular way", difficulty: "easy", sentence: "Hard work will determine your success.", commonMisspellings: ["deterime"] },
  { word: "develop", definition: "To grow or cause to grow", difficulty: "easy", sentence: "We need to develop a new strategy.", commonMisspellings: ["develope"] },
  { word: "disappear", definition: "To cease to be visible", difficulty: "easy", sentence: "The magician made the coin disappear.", commonMisspellings: ["disapear"] },
  { word: "discipline", definition: "The practice of training to obey rules", difficulty: "easy", origin: "Latin", sentence: "Athletes need strict discipline.", commonMisspellings: ["disipline"] },
  { word: "distinguish", definition: "To recognize as different", difficulty: "easy", sentence: "Can you distinguish between the two?", commonMisspellings: ["distiguish"] },
  { word: "efficiency", definition: "The state of achieving maximum productivity", difficulty: "easy", sentence: "The new system improved efficiency.", commonMisspellings: ["efficency"] },
  { word: "eliminate", definition: "To completely remove or get rid of", difficulty: "easy", sentence: "We need to eliminate the errors.", commonMisspellings: ["eliminite"] },
  { word: "enthusiasm", definition: "Intense enjoyment or interest", difficulty: "easy", sentence: "Her enthusiasm was contagious.", commonMisspellings: ["enthusiam"] },
  { word: "essential", definition: "Absolutely necessary", difficulty: "easy", sentence: "Water is essential for survival.", commonMisspellings: ["esential"] },
  { word: "evidence", definition: "The available facts supporting a belief", difficulty: "easy", sentence: "The evidence pointed to the suspect.", commonMisspellings: ["evidance"] },
  { word: "excellent", definition: "Extremely good; outstanding", difficulty: "easy", sentence: "She did an excellent job.", commonMisspellings: ["excelent"] },
  { word: "fascinate", definition: "To attract and hold attention", difficulty: "easy", sentence: "The documentary will fascinate you.", commonMisspellings: ["facinate"] },
  { word: "fortunate", definition: "Favored by luck", difficulty: "easy", sentence: "We were fortunate to find shelter.", commonMisspellings: ["fortuate"] },
  { word: "frequent", definition: "Occurring often", difficulty: "easy", sentence: "Frequent exercise improves health.", commonMisspellings: ["frequant"] },
  { word: "generous", definition: "Showing a readiness to give", difficulty: "easy", sentence: "He made a generous donation.", commonMisspellings: ["generus"] },
  { word: "genuine", definition: "Truly what something is said to be", difficulty: "easy", sentence: "The painting was genuine.", commonMisspellings: ["genuiene"] },
  { word: "grateful", definition: "Feeling or showing thanks", difficulty: "easy", sentence: "I'm grateful for your help.", commonMisspellings: ["greatful"] },
  { word: "guidance", definition: "Advice or information aimed at resolving a problem", difficulty: "easy", sentence: "She sought guidance from her mentor.", commonMisspellings: ["guidence"] },
  { word: "harass", definition: "To subject to unwanted behavior", difficulty: "easy", origin: "French", sentence: "It is illegal to harass someone.", commonMisspellings: ["harrass"] },
  { word: "hygiene", definition: "Conditions or practices conducive to health", difficulty: "easy", sentence: "Good hygiene prevents illness.", commonMisspellings: ["hygene"] },
  { word: "ignorance", definition: "Lack of knowledge or information", difficulty: "easy", sentence: "Ignorance of the law is no excuse.", commonMisspellings: ["ignoranse"] },
  { word: "imaginary", definition: "Existing only in the imagination", difficulty: "easy", sentence: "The child had an imaginary friend.", commonMisspellings: ["imagenary"] },
  { word: "imitate", definition: "To take or follow as a model", difficulty: "easy", sentence: "Children often imitate their parents.", commonMisspellings: ["immitate"] },
  { word: "incredible", definition: "Impossible to believe", difficulty: "easy", sentence: "The view from the top was incredible.", commonMisspellings: ["incredable"] },
  { word: "influence", definition: "The capacity to have an effect on someone", difficulty: "easy", sentence: "Music has a strong influence on mood.", commonMisspellings: ["influance"] },
  { word: "innocence", definition: "The quality of not being guilty", difficulty: "easy", sentence: "He maintained his innocence throughout.", commonMisspellings: ["inocence"] },
  { word: "intelligent", definition: "Having a high mental capacity", difficulty: "easy", sentence: "She is one of the most intelligent students.", commonMisspellings: ["inteligent"] },
  { word: "interference", definition: "The action of interfering", difficulty: "easy", sentence: "The interference disrupted the signal.", commonMisspellings: ["interferance"] },
  { word: "irresistible", definition: "Too attractive to be resisted", difficulty: "easy", sentence: "The chocolate cake was irresistible.", commonMisspellings: ["irresistable"] },
  { word: "itinerary", definition: "A planned route or journey", difficulty: "easy", sentence: "Check the itinerary for tomorrow.", commonMisspellings: ["itinerery"] },

  // --- MEDIUM (50+) ---
  { word: "accommodate", definition: "To provide lodging or room for", difficulty: "medium", hint: "Double c, double m", origin: "Latin", commonMisspellings: ["acommodate", "acommodate"] },
  { word: "acknowledgment", definition: "Acceptance of the truth of something", difficulty: "medium", commonMisspellings: ["acknowledgement"] },
  { word: "acquaintance", definition: "A person one knows slightly", difficulty: "medium", hint: "Ac-quaint-ance", origin: "Latin", commonMisspellings: ["aquaintance"] },
  { word: "bureaucracy", definition: "A system of government with many complex rules", difficulty: "medium", origin: "French", commonMisspellings: ["bureacracy"] },
  { word: "Caribbean", definition: "The region consisting of the Caribbean Sea and its islands", difficulty: "medium", origin: "Indigenous", commonMisspellings: ["Carribean", "Carribbean"] },
  { word: "catastrophe", definition: "A sudden disaster causing great damage", difficulty: "medium", origin: "Greek", commonMisspellings: ["catastrophy"] },
  { word: "cemetery", definition: "A burial ground for the dead", difficulty: "medium", origin: "Greek", commonMisspellings: ["cemetary", "cemetary"] },
  { word: "changeable", definition: "Liable to change; unpredictable", difficulty: "medium", hint: "Keep the 'e'", commonMisspellings: ["changable"] },
  { word: "collectible", definition: "An item valued and sought by collectors", difficulty: "medium", commonMisspellings: ["collectable"] },
  { word: "consensus", definition: "A general agreement among a group", difficulty: "medium", origin: "Latin", commonMisspellings: ["concensus", "consencus"] },
  { word: "correspondence", definition: "Communication by exchanging letters", difficulty: "medium", hint: "Double r, -ence", commonMisspellings: ["correspondance"] },
  { word: "dilemma", definition: "A situation requiring a difficult choice", difficulty: "medium", origin: "Greek", commonMisspellings: ["dilemna"] },
  { word: "disappearance", definition: "The act of ceasing to be visible", difficulty: "medium", hint: "Double p", commonMisspellings: ["disapearance"] },
  { word: "embarrassment", definition: "A feeling of self-consciousness or shame", difficulty: "medium", hint: "Double r, double s", commonMisspellings: ["embarassment"] },
  { word: "exaggerate", definition: "To represent as greater than it actually is", difficulty: "medium", hint: "Double g", origin: "Latin", commonMisspellings: ["exagerate"] },
  { word: "fluorescent", definition: "Emitting light when exposed to radiation", difficulty: "medium", origin: "Latin", commonMisspellings: ["florescent", "flourescent"] },
  { word: "hierarchy", definition: "A system of ranking one above another", difficulty: "medium", origin: "Greek", commonMisspellings: ["heirarchy", "hierachy"] },
  { word: "idiosyncrasy", definition: "A distinctive individual behavior or characteristic", difficulty: "medium", origin: "Greek", commonMisspellings: ["idiosyncracy"] },
  { word: "jewelry", definition: "Personal ornaments such as rings and necklaces", difficulty: "medium", commonMisspellings: ["jewlery", "jewelery"] },
  { word: "lieutenant", definition: "A military officer of middle rank", difficulty: "medium", origin: "French", commonMisspellings: ["leutenant", "lieutanant"] },
  { word: "maintenance", definition: "The process of preserving a condition", difficulty: "medium", hint: "Main-tain-ance", commonMisspellings: ["maintainance", "maintanance"] },
  { word: "mischievous", definition: "Causing or showing a tendency to cause trouble playfully", difficulty: "medium", hint: "Mis-chief-ous", commonMisspellings: ["mischievious", "mischevous"] },
  { word: "noticeable", definition: "Easily seen or noticed", difficulty: "medium", hint: "Notice + able", commonMisspellings: ["noticable"] },
  { word: "perseverance", definition: "Persistence in doing something despite difficulty", difficulty: "medium", origin: "Latin", commonMisspellings: ["perserverance"] },
  { word: "questionnaire", definition: "A set of printed questions for a survey", difficulty: "medium", origin: "French", commonMisspellings: ["questionaire", "questionnair"] },
  { word: "Renaissance", definition: "The revival of art and learning in Europe", difficulty: "medium", origin: "French", commonMisspellings: ["Renaissence", "Renaissanse"] },
  { word: "rhythm", definition: "A strong regular repeated pattern of sound", difficulty: "medium", hint: "No vowels except y", origin: "Greek", commonMisspellings: ["rythm", "rythym"] },
  { word: "surveillance", definition: "Close observation of a person or group", difficulty: "medium", origin: "French", commonMisspellings: ["surveilance"] },
  { word: "technique", definition: "A way of carrying out a particular task", difficulty: "medium", origin: "Greek", commonMisspellings: ["technic"] },
  { word: "threshold", definition: "A strip of wood or stone forming the bottom of a doorway", difficulty: "medium", hint: "One h", commonMisspellings: ["threshhold"] },
  { word: "twelfth", definition: "Constituting number twelve in a sequence", difficulty: "medium", hint: "Twel-fth", commonMisspellings: ["twelth"] },
  { word: "unnecessary", definition: "Not required; superfluous", difficulty: "medium", hint: "Double n", commonMisspellings: ["unecessary", "unneccessary"] },
  { word: "vacuum", definition: "A space entirely devoid of matter", difficulty: "medium", origin: "Latin", commonMisspellings: ["vaccum", "vacume"] },
  { word: "weather", definition: "The state of the atmosphere", difficulty: "medium", commonMisspellings: ["wether"] },
  { word: "whether", definition: "Expressing a doubt or choice", difficulty: "medium", commonMisspellings: ["wether"] },
  { word: "yacht", definition: "A medium-sized sailboat used for racing", difficulty: "medium", origin: "Dutch", commonMisspellings: ["yatch"] },
  { word: "accessible", definition: "Able to be reached or used", difficulty: "medium", commonMisspellings: ["accessable"] },
  { word: "accidentally", definition: "By chance; inadvertently", difficulty: "medium", commonMisspellings: ["accidently"] },
  { word: "accomplish", definition: "To achieve or complete successfully", difficulty: "medium", hint: "Double c, double l", commonMisspellings: ["acomplish"] },
  { word: "accordance", definition: "Conformity or agreement", difficulty: "medium" },
  { word: "accumulate", definition: "To gather or build up", difficulty: "medium", origin: "Latin" },
  { word: "accuracy", definition: "The quality of being correct or precise", difficulty: "medium", commonMisspellings: ["accurancy"] },
  { word: "accustomed", definition: "Customary; usual", difficulty: "medium" },
  { word: "achievement", definition: "A thing done successfully", difficulty: "medium", commonMisspellings: ["acheivement"] },
  { word: "acquire", definition: "To buy or obtain", difficulty: "medium", origin: "Latin", commonMisspellings: ["aquire"] },
  { word: "acquisition", definition: "An asset or object bought or obtained", difficulty: "medium" },
  { word: "adequate", definition: "Satisfactory or acceptable", difficulty: "medium", origin: "Latin" },
  { word: "adjacent", definition: "Next to or adjoining", difficulty: "medium", origin: "Latin" },
  { word: "adjustment", definition: "A small alteration or modification", difficulty: "medium" },
  { word: "advertisement", definition: "A notice or announcement promoting something", difficulty: "medium", commonMisspellings: ["advertisment"] },
  { word: "aggressive", definition: "Ready or likely to attack", difficulty: "medium", hint: "Double g", commonMisspellings: ["agressive"] },
  { word: "alcohol", definition: "A colorless volatile liquid used in drinks", difficulty: "medium", origin: "Arabic" },
  { word: "algorithm", definition: "A process or set of rules for calculation", difficulty: "medium", origin: "Arabic" },
  { word: "aluminum", definition: "A lightweight silvery-white metal", difficulty: "medium", commonMisspellings: ["aluminium"] },
  { word: "amateur", definition: "A person who engages in a pursuit without payment", difficulty: "medium", origin: "French", commonMisspellings: ["amature"] },
  { word: "analysis", definition: "Detailed examination of the elements of something", difficulty: "medium", origin: "Greek", commonMisspellings: ["analisis"] },
  { word: "anonymous", definition: "Not identified by name", difficulty: "medium", origin: "Greek", commonMisspellings: ["anonimous"] },
  { word: "apartment", definition: "A suite of rooms forming one residence", difficulty: "medium", commonMisspellings: ["apartement"] },
  { word: "apparatus", definition: "The technical equipment needed for a particular activity", difficulty: "medium", origin: "Latin" },
  { word: "appearance", definition: "The way that someone or something looks", difficulty: "medium", commonMisspellings: ["appearence"] },
  { word: "appendix", definition: "A section of supplementary material at the end of a book", difficulty: "medium", origin: "Latin" },
  { word: "appreciation", definition: "Recognition of the value of something", difficulty: "medium" },
  { word: "appropriate", definition: "Suitable or proper", difficulty: "medium", origin: "Latin", commonMisspellings: ["apropriate"] },
  { word: "approximate", definition: "Close to the actual but not exact", difficulty: "medium", origin: "Latin" },
  { word: "architect", definition: "A person who designs buildings", difficulty: "medium", origin: "Greek", commonMisspellings: ["architecht"] },
  { word: "arithmetic", definition: "The branch of mathematics dealing with numbers", difficulty: "medium", origin: "Greek", commonMisspellings: ["arithmentic"] },
  { word: "assistant", definition: "A person who helps in particular work", difficulty: "medium", commonMisspellings: ["asistant"] },
  { word: "association", definition: "A group of people organized for a joint purpose", difficulty: "medium" },
  { word: "assumption", definition: "A thing that is accepted as true", difficulty: "medium" },
  { word: "athlete", definition: "A person skilled in physical exercise", difficulty: "medium", origin: "Greek", commonMisspellings: ["athelete"] },
  { word: "atmosphere", definition: "The envelope of gases surrounding the earth", difficulty: "medium", origin: "Greek", commonMisspellings: ["atmospher"] },
  { word: "attendance", definition: "The action of being present at a place", difficulty: "medium" },
  { word: "audience", definition: "The assembled spectators or listeners", difficulty: "medium", origin: "Latin" },
  { word: "autumn", definition: "The season after summer", difficulty: "medium", origin: "Latin", commonMisspellings: ["autum"] },
  { word: "average", definition: "The result obtained by adding quantities and dividing by the number of quantities", difficulty: "medium", origin: "Arabic" },
  { word: "bachelor", definition: "A man who is not and has never been married", difficulty: "medium", origin: "French", commonMisspellings: ["batchelor"] },
  { word: "bacteria", definition: "Microscopic single-celled organisms", difficulty: "medium", origin: "Greek" },
  { word: "bankruptcy", definition: "The state of being unable to pay debts", difficulty: "medium", commonMisspellings: ["bankrupcy"] },
  { word: "beautiful", definition: "Pleasing to the senses or mind", difficulty: "medium", commonMisspellings: ["beatiful"] },
  { word: "beneficial", definition: "Favorable or advantageous", difficulty: "medium", origin: "Latin" },
  { word: "boundary", definition: "A line that marks the limits of an area", difficulty: "medium", commonMisspellings: ["boundry"] },

  // --- HARD (50+) ---
  { word: "acquiesce", definition: "To accept something reluctantly without protest", difficulty: "hard", origin: "Latin", commonMisspellings: ["acquiese", "aquiesce"] },
  { word: "bourgeois", definition: "Of or characteristic of the middle class", difficulty: "hard", origin: "French", commonMisspellings: ["bourgeoise"] },
  { word: "camouflage", definition: "The disguising of military personnel or equipment", difficulty: "hard", origin: "French", commonMisspellings: ["camoflage", "camoflauge"] },
  { word: "connoisseur", definition: "An expert judge in matters of fine art or taste", difficulty: "hard", origin: "French", commonMisspellings: ["connoisseur", "conoisseur"] },
  { word: "conscientious", definition: "Wishing to do what is right; thorough", difficulty: "hard", origin: "Latin", commonMisspellings: ["consciencious"] },
  { word: "desiccate", definition: "To remove moisture from something", difficulty: "hard", origin: "Latin", commonMisspellings: ["dessicate", "desicate"] },
  { word: "ecstasy", definition: "An overwhelming feeling of great happiness", difficulty: "hard", origin: "Greek", commonMisspellings: ["ecstacy", "extacy"] },
  { word: "entrepreneur", definition: "A person who sets up a business taking on financial risks", difficulty: "hard", origin: "French", commonMisspellings: ["entrepeneur", "entreprenuer"], sentence: "She became a successful entrepreneur at age 25." },
  { word: "hemorrhage", definition: "An escape of blood from a ruptured blood vessel", difficulty: "hard", origin: "Greek", commonMisspellings: ["hemorage", "haemorrhage"] },
  { word: "hors d'oeuvre", definition: "A small savory dish served as an appetizer", difficulty: "hard", origin: "French" },
  { word: "inoculate", definition: "To treat with a vaccine to produce immunity", difficulty: "hard", origin: "Latin", commonMisspellings: ["innoculate"] },
  { word: "jeopardize", definition: "To put at risk of loss or harm", difficulty: "hard", origin: "French", commonMisspellings: ["jeopardise"] },
  { word: "labyrinth", definition: "A complicated irregular network of passages", difficulty: "hard", origin: "Greek", commonMisspellings: ["labrynth"] },
  { word: "liaison", definition: "Communication or cooperation between groups", difficulty: "hard", origin: "French", commonMisspellings: ["liason", "liason"] },
  { word: "maneuver", definition: "A movement or series of moves requiring skill", difficulty: "hard", origin: "French", commonMisspellings: ["manoeuvre", "manuver"] },
  { word: "mnemonic", definition: "A device such as a pattern to aid memory", difficulty: "hard", origin: "Greek", commonMisspellings: ["nemonic", "pnemonic"] },
  { word: "nonchalant", definition: "Feeling or appearing casually calm", difficulty: "hard", origin: "French", commonMisspellings: ["nonchelant"] },
  { word: "onomatopoeia", definition: "The formation of a word from a sound", difficulty: "hard", origin: "Greek", commonMisspellings: ["onomatopoea", "onomatopia"] },
  { word: "pneumonia", definition: "A lung infection causing inflammation", difficulty: "hard", origin: "Greek", commonMisspellings: ["pnemonia", "neumonia"] },
  { word: "pseudonym", definition: "A fictitious name used by an author", difficulty: "hard", origin: "Greek", commonMisspellings: ["pseudonim", "seudonym"] },
  { word: "reconnaissance", definition: "Military observation of a region to locate an enemy", difficulty: "hard", origin: "French", commonMisspellings: ["reconaissance", "reconnaissance"] },
  { word: "rendezvous", definition: "A meeting at an agreed time and place", difficulty: "hard", origin: "French", commonMisspellings: ["rendevous", "rendezous"] },
  { word: "sacrilegious", definition: "Violating or showing disrespect for something sacred", difficulty: "hard", origin: "Latin", commonMisspellings: ["sacreligious"] },
  { word: "silhouette", definition: "The dark shape of something visible against a lighter background", difficulty: "hard", origin: "French", commonMisspellings: ["silouette", "silhoutte"] },
  { word: "surreptitious", definition: "Kept secret because it would not be approved of", difficulty: "hard", origin: "Latin", commonMisspellings: ["surreptious"] },
  { word: "thoroughfare", definition: "A main road in a town or city", difficulty: "hard", commonMisspellings: ["throughfare", "thoroghfare"] },
  { word: "unconscious", definition: "Not awake and aware of one's surroundings", difficulty: "hard", commonMisspellings: ["unconcious", "unconsious"] },
  { word: "vicissitude", definition: "A change of circumstances, typically unwelcome", difficulty: "hard", origin: "Latin", commonMisspellings: ["vicisitude"] },
  { word: "worcestershire", definition: "A fermented liquid condiment originating from England", difficulty: "hard", origin: "English" },
  { word: "abbreviate", definition: "To shorten a word or phrase", difficulty: "hard", origin: "Latin" },
  { word: "abundance", definition: "A very large quantity of something", difficulty: "hard" },
  { word: "accommodation", definition: "A room or building for lodging", difficulty: "hard", commonMisspellings: ["acommodation"] },
  { word: "acoustic", definition: "Relating to sound or the sense of hearing", difficulty: "hard", origin: "Greek" },
  { word: "aesthetic", definition: "Concerned with beauty or the appreciation of beauty", difficulty: "hard", origin: "Greek", commonMisspellings: ["esthetic"] },
  { word: "affidavit", definition: "A written statement confirmed by oath", difficulty: "hard", origin: "Latin" },
  { word: "aggressive", definition: "Ready or likely to attack", difficulty: "hard" },
  { word: "allegory", definition: "A story with a symbolic meaning", difficulty: "hard", origin: "Greek" },
  { word: "amphitheater", definition: "An open circular or oval building with tiers of seats", difficulty: "hard", origin: "Greek", commonMisspellings: ["amphitheatre"] },
  { word: "anachronism", definition: "Something belonging to a different period", difficulty: "hard", origin: "Greek" },
  { word: "anomaly", definition: "Something that deviates from what is standard", difficulty: "hard", origin: "Greek" },
  { word: "antiquated", definition: "Old-fashioned or outdated", difficulty: "hard" },
  { word: "apothecary", definition: "A person who prepared and sold medicines", difficulty: "hard", origin: "Greek" },
  { word: "archaeology", definition: "The study of human history through excavation", difficulty: "hard", origin: "Greek", commonMisspellings: ["archeology"] },
  { word: "asthma", definition: "A respiratory condition marked by breathing difficulty", difficulty: "hard", origin: "Greek", commonMisspellings: ["asthma"] },
  { word: "asymmetric", definition: "Lacking symmetry", difficulty: "hard", origin: "Greek" },
  { word: "belligerent", definition: "Hostile and aggressive", difficulty: "hard", origin: "Latin" },
  { word: "benediction", definition: "The utterance of a blessing", difficulty: "hard", origin: "Latin" },
  { word: "bureaucrat", definition: "An official in a government department", difficulty: "hard", origin: "French" },
  { word: "caffeine", definition: "A stimulant found in tea and coffee", difficulty: "hard", origin: "Arabic", commonMisspellings: ["caffiene", "caffine"] },
  { word: "campaign", definition: "An organized course of action", difficulty: "hard", origin: "Latin", commonMisspellings: ["campain"] },
  { word: "cantaloupe", definition: "A type of orange melon", difficulty: "hard", origin: "French", commonMisspellings: ["canteloupe", "cantalope"] },
  { word: "carbohydrate", definition: "A compound that is a source of energy", difficulty: "hard", origin: "Latin" },
  { word: "caricature", definition: "A picture exaggerating someone's features", difficulty: "hard", origin: "Italian" },
  { word: "cartilage", definition: "Firm, flexible connective tissue", difficulty: "hard", origin: "Latin" },
  { word: "catastrophic", definition: "Involving or causing sudden great damage", difficulty: "hard", origin: "Greek" },
  { word: "chaos", definition: "Complete disorder and confusion", difficulty: "hard", origin: "Greek", commonMisspellings: ["kaos"] },
  { word: "cholesterol", definition: "A compound in blood and cells", difficulty: "hard", origin: "Greek", commonMisspellings: ["cholestorol"] },
  { word: "colonel", definition: "A rank of officer in the army", difficulty: "hard", origin: "Italian", commonMisspellings: ["kernel"] },
  { word: "conscience", definition: "An inner feeling of right and wrong", difficulty: "hard" },
  { word: "consensus", definition: "General agreement", difficulty: "hard" },
  { word: "controversy", definition: "Disagreement about a matter of opinion", difficulty: "hard", origin: "Latin", commonMisspellings: ["contraversy"] },
  { word: "convenience", definition: "The state of being able to proceed with something with little effort", difficulty: "hard", commonMisspellings: ["convinience"] },
  { word: "corollary", definition: "A proposition that follows from one already proven", difficulty: "hard", origin: "Latin" },
  { word: "courageous", definition: "Not deterred by danger or pain", difficulty: "hard", commonMisspellings: ["corageous"] },
  { word: "courteous", definition: "Polite and considerate", difficulty: "hard", commonMisspellings: ["curteous"] },
  { word: "criticize", definition: "To indicate the faults of", difficulty: "hard", commonMisspellings: ["criticise"] },
  { word: "deceive", definition: "To cause to believe what is not true", difficulty: "hard", hint: "i before e except after c", commonMisspellings: ["decieve"] },
  { word: "deductible", definition: "Able to be deducted", difficulty: "hard", commonMisspellings: ["deductable"] },
  { word: "definite", definition: "Clearly stated or decided", difficulty: "hard", commonMisspellings: ["definate"] },
  { word: "democracy", definition: "A system of government by the whole population", difficulty: "hard", origin: "Greek" },
  { word: "dependence", definition: "The state of relying on something", difficulty: "hard", commonMisspellings: ["dependance"] },
  { word: "descendant", definition: "A person descended from a specified ancestor", difficulty: "hard", commonMisspellings: ["descendent"] },
  { word: "dilemma", definition: "A situation requiring a difficult choice", difficulty: "hard" },
  { word: "discern", definition: "To perceive or recognize something", difficulty: "hard", origin: "Latin" },
  { word: "discipline", definition: "Training to obey rules or a code of behavior", difficulty: "hard", origin: "Latin", commonMisspellings: ["disipline"] },
  { word: "ecclesiastical", definition: "Relating to the Christian Church or its clergy", difficulty: "hard", origin: "Greek", sentence: "The building had an ecclesiastical design." },

  // --- MORE MEDIUM (with sentences) ---
  { word: "conscience", definition: "An inner feeling of right and wrong", difficulty: "medium", sentence: "His conscience would not let him lie.", commonMisspellings: ["concience"] },
  { word: "perseverance", definition: "Persistence despite difficulty", difficulty: "medium", origin: "Latin", sentence: "Perseverance is key to success.", commonMisspellings: ["perserverance"] },
  { word: "rhythm", definition: "A strong regular repeated pattern of sound", difficulty: "medium", origin: "Greek", sentence: "The rhythm of the music was catchy.", commonMisspellings: ["rythm", "rythym"] },
  { word: "bureaucracy", definition: "A system of government with many complex rules", difficulty: "medium", origin: "French", sentence: "The bureaucracy slowed down the process.", commonMisspellings: ["bureacracy"] },
  { word: "liaison", definition: "Communication between groups", difficulty: "medium", origin: "French", sentence: "She served as liaison between the two teams.", commonMisspellings: ["liason"] },
  { word: "maneuver", definition: "A movement requiring skill", difficulty: "medium", origin: "French", sentence: "The pilot executed a difficult maneuver.", commonMisspellings: ["manoeuvre"] },
  { word: "rendezvous", definition: "A meeting at an agreed time and place", difficulty: "medium", origin: "French", sentence: "They planned a rendezvous at noon.", commonMisspellings: ["rendevous"] },
  { word: "silhouette", definition: "The dark shape of something against a lighter background", difficulty: "medium", origin: "French", sentence: "Her silhouette appeared in the doorway.", commonMisspellings: ["silouette"] },
  { word: "mnemonic", definition: "A device to aid memory", difficulty: "medium", origin: "Greek", sentence: "Roy G. Biv is a mnemonic for the rainbow.", commonMisspellings: ["nemonic"] },
  { word: "pneumonia", definition: "A lung infection causing inflammation", difficulty: "medium", origin: "Greek", sentence: "He was hospitalized with pneumonia.", commonMisspellings: ["pnemonia"] },
  { word: "pseudonym", definition: "A fictitious name used by an author", difficulty: "medium", origin: "Greek", sentence: "She wrote under a pseudonym.", commonMisspellings: ["pseudonim"] },
  { word: "reconnaissance", definition: "Military observation of a region", difficulty: "medium", origin: "French", sentence: "The squadron flew a reconnaissance mission.", commonMisspellings: ["reconaissance"] },
  { word: "sacrilegious", definition: "Showing disrespect for something sacred", difficulty: "medium", origin: "Latin", sentence: "Some considered the act sacrilegious.", commonMisspellings: ["sacreligious"] },
  { word: "surreptitious", definition: "Kept secret because not approved", difficulty: "medium", origin: "Latin", sentence: "She took a surreptitious glance at her notes.", commonMisspellings: ["surreptious"] },
  { word: "vicissitude", definition: "A change of circumstances, typically unwelcome", difficulty: "medium", origin: "Latin", sentence: "The vicissitudes of life taught him resilience.", commonMisspellings: ["vicisitude"] },

  // --- EXPERT (30+) ---
  { word: "antediluvian", definition: "Of or belonging to the time before the biblical flood; very old", difficulty: "expert", origin: "Latin" },
  { word: "appoggiatura", definition: "A grace note in music that delays the next note", difficulty: "expert", origin: "Italian" },
  { word: "bourgeoisie", definition: "The middle class, typically with materialistic values", difficulty: "expert", origin: "French" },
  { word: "chrysanthemum", definition: "A plant of the daisy family with brightly colored flowers", difficulty: "expert", origin: "Greek", commonMisspellings: ["chrysanthamum"] },
  { word: "chiaroscuro", definition: "The treatment of light and shade in drawing and painting", difficulty: "expert", origin: "Italian" },
  { word: "diphtheria", definition: "An acute infectious disease causing inflammation", difficulty: "expert", origin: "Greek", commonMisspellings: ["diphtheria"] },
  { word: "ecclesiastical", definition: "Relating to the Christian Church or its clergy", difficulty: "expert", origin: "Greek" },
  { word: "pharaoh", definition: "A ruler in ancient Egypt", difficulty: "expert", origin: "Egyptian", commonMisspellings: ["pharoah", "faroh"] },
  { word: "phlegmatic", definition: "Having a calm temperament; unemotional", difficulty: "expert", origin: "Greek", commonMisspellings: ["phlegmatic"] },
  { word: "pterodactyl", definition: "A type of flying reptile from the late Jurassic period", difficulty: "expert", origin: "Greek", commonMisspellings: ["terodactyl"] },
  { word: "rhododendron", definition: "A shrub or small tree with large clusters of flowers", difficulty: "expert", origin: "Greek", commonMisspellings: ["rhodedendron"] },
  { word: "schadenfreude", definition: "Pleasure derived from another person's misfortune", difficulty: "expert", origin: "German" },
  { word: "sphygmomanometer", definition: "An instrument for measuring blood pressure", difficulty: "expert", origin: "Greek", sentence: "The nurse used a sphygmomanometer to check his blood pressure." },
  { word: "staphylococcus", definition: "A bacterium causing pus formation", difficulty: "expert", origin: "Greek", sentence: "The infection was caused by staphylococcus." },
  { word: "subpoena", definition: "A writ ordering a person to attend court", difficulty: "expert", origin: "Latin", commonMisspellings: ["subpena"], sentence: "He received a subpoena to testify." },
  { word: "sycophant", definition: "A person who flatters someone important", difficulty: "expert", origin: "Greek", commonMisspellings: ["sycophant"], sentence: "The sycophant praised every decision." },
  { word: "teetotaler", definition: "A person who never drinks alcohol", difficulty: "expert", commonMisspellings: ["teetotaller"], sentence: "As a teetotaler, she declined the wine." },
  { word: "thoroughbred", definition: "A pure breed of horse", difficulty: "expert", commonMisspellings: ["thoroghbred"], sentence: "The thoroughbred won the race." },
  { word: "unequivocally", definition: "In a way that leaves no doubt", difficulty: "expert", commonMisspellings: ["unequivically"], sentence: "She unequivocally denied the accusation." },
  { word: "verisimilitude", definition: "The appearance of being true or real", difficulty: "expert", origin: "Latin", sentence: "The film achieved great verisimilitude." },
  { word: "xylophone", definition: "A musical instrument with wooden bars struck by mallets", difficulty: "expert", origin: "Greek", commonMisspellings: ["xylaphone"], sentence: "The child played a tune on the xylophone." },
  { word: "zoology", definition: "The scientific study of animals", difficulty: "expert", origin: "Greek", commonMisspellings: ["zoology"] },
  { word: "abstemious", definition: "Not self-indulgent, especially regarding food and drink", difficulty: "expert", origin: "Latin" },
  { word: "anemone", definition: "A plant of the buttercup family with brightly colored flowers", difficulty: "expert", origin: "Greek", commonMisspellings: ["enemone"] },
  { word: "ascetic", definition: "Characterized by severe self-discipline", difficulty: "expert", origin: "Greek" },
  { word: "asphyxiate", definition: "To kill or be killed by deprivation of oxygen", difficulty: "expert", origin: "Greek" },
  { word: "bacillus", definition: "A rod-shaped bacterium", difficulty: "expert", origin: "Latin" },
  { word: "belligerence", definition: "Aggressive or warlike behavior", difficulty: "expert", origin: "Latin" },
  { word: "bergamot", definition: "An aromatic citrus fruit", difficulty: "expert", origin: "Turkish" },
  { word: "brusque", definition: "Abrupt or offhand in speech or manner", difficulty: "expert", origin: "French", commonMisspellings: ["brusk"] },
  { word: "cavalry", definition: "Soldiers who fight on horseback", difficulty: "expert", origin: "Italian", commonMisspellings: ["calvary"] },
  { word: "colloquial", definition: "Used in ordinary or familiar conversation", difficulty: "expert", origin: "Latin" },
  { word: "conscientious", definition: "Wishing to do what is right; thorough", difficulty: "expert" },
  { word: "counterfeit", definition: "Made in exact imitation of something valuable", difficulty: "expert", origin: "French", commonMisspellings: ["counterfiet"] },
  { word: "dachshund", definition: "A breed of dog with a long body and short legs", difficulty: "expert", origin: "German", commonMisspellings: ["dachsund", "dashund"] },
  { word: "demagogue", definition: "A political leader who appeals to popular desires", difficulty: "expert", origin: "Greek" },
  { word: "deteriorate", definition: "To become progressively worse", difficulty: "expert", origin: "Latin", commonMisspellings: ["deteriate"] },
  { word: "eighth", definition: "Constituting number eight in a sequence", difficulty: "expert", commonMisspellings: ["eigth"] },
  { word: "exacerbate", definition: "To make a problem or situation worse", difficulty: "expert", origin: "Latin", commonMisspellings: ["exasperate"] },
  { word: "fascinating", definition: "Extremely interesting", difficulty: "expert", commonMisspellings: ["facinating"] },
  { word: "gauge", definition: "An instrument that measures and gives a visual display", difficulty: "expert", origin: "French", commonMisspellings: ["guage"] },
  { word: "guttural", definition: "Of a consonant produced in the throat", difficulty: "expert", origin: "Latin" },
  { word: "harass", definition: "To subject to aggressive pressure or intimidation", difficulty: "expert", origin: "French", commonMisspellings: ["harrass"] },
  { word: "heinous", definition: "Utterly odious or wicked", difficulty: "expert", origin: "French", commonMisspellings: ["henious"] },
  { word: "hierarchy", definition: "A system of ranking one above another", difficulty: "expert" },
  { word: "ignominious", definition: "Deserving or causing public disgrace", difficulty: "expert", origin: "Latin" },
  { word: "iridescent", definition: "Showing luminous colors that seem to change", difficulty: "expert", origin: "Latin" },
  { word: "kaleidoscope", definition: "A tube containing mirrors and pieces of colored glass", difficulty: "expert", origin: "Greek" },
  { word: "laryngitis", definition: "Inflammation of the larynx", difficulty: "expert", origin: "Greek" },
  { word: "miscellaneous", definition: "Of mixed character; diverse", difficulty: "expert", origin: "Latin", commonMisspellings: ["miscellanous"] },
  { word: "nauseous", definition: "Affected with nausea", difficulty: "expert", origin: "Greek", commonMisspellings: ["nausous"] },
  { word: "obsequious", definition: "Obedient or attentive to an excessive degree", difficulty: "expert", origin: "Latin" },
  { word: "paraphernalia", definition: "Miscellaneous articles needed for a particular activity", difficulty: "expert", origin: "Greek" },
  { word: "phenomenon", definition: "A fact or situation that is observed to exist", difficulty: "expert", origin: "Greek", commonMisspellings: ["phenomenom", "phenomena"] },
  { word: "prestigious", definition: "Inspiring respect and admiration", difficulty: "expert", origin: "Latin", commonMisspellings: ["prestigous"] },
  { word: "pronunciation", definition: "The way in which a word is pronounced", difficulty: "expert", commonMisspellings: ["pronounciation"] },
  { word: "psoriasis", definition: "A skin condition causing red, flaky patches", difficulty: "expert", origin: "Greek" },
  { word: "queue", definition: "A line or sequence of people or vehicles", difficulty: "expert", origin: "French", commonMisspellings: ["que"] },
  { word: "restaurant", definition: "A place where meals are served", difficulty: "expert" },
  { word: "rhetoric", definition: "The art of effective or persuasive speaking", difficulty: "expert", origin: "Greek" },
  { word: "sophomore", definition: "A second-year university or high school student", difficulty: "expert", origin: "Greek", commonMisspellings: ["sophmore"] },
  { word: "tortilla", definition: "A thin flatbread made from corn or flour", difficulty: "expert", origin: "Spanish", commonMisspellings: ["tortilla"] },
  { word: "tranquil", definition: "Free from disturbance; calm", difficulty: "expert", origin: "Latin", commonMisspellings: ["tranquil"] },
  { word: "ubiquitous", definition: "Present, appearing, or found everywhere", difficulty: "expert", origin: "Latin" },
  { word: "vaccinate", definition: "To treat with a vaccine to produce immunity", difficulty: "expert", origin: "Latin" },
  { word: "vengeance", definition: "Punishment inflicted in retaliation", difficulty: "expert", origin: "Latin", commonMisspellings: ["vengance"] },
  { word: "wholly", definition: "Entirely; fully", difficulty: "expert", commonMisspellings: ["wholely", "wholy"] },
];
