/**
 * Typing Race passage library — 100+ passages across famous quotes,
 * tongue twisters, and descriptive prose. All between 30–60 words.
 */
export const PASSAGES: string[] = [
  // — Famous quotes —
  "The only way to do great work is to love what you do. If you have not found it yet, keep looking. Do not settle. As with all matters of the heart, you will know when you find it.",
  "In the middle of every difficulty lies opportunity. The measure of intelligence is the ability to change. Imagination is more important than knowledge, for knowledge is limited.",
  "It does not matter how slowly you go as long as you do not stop. Our greatest glory is not in never falling, but in rising every time we fall.",
  "The future belongs to those who believe in the beauty of their dreams. You must do the thing you think you cannot do. Life is not measured by the number of breaths we take.",
  "Twenty years from now you will be more disappointed by the things that you did not do than by the ones you did. So throw off the bowlines and sail away from the safe harbor.",
  "Success is not final, failure is not fatal. It is the courage to continue that counts. The pessimist sees difficulty in every opportunity; the optimist sees opportunity in every difficulty.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. The way to get started is to quit talking and begin doing.",
  "Life is what happens when you are busy making other plans. In the end it is not the years in your life that count but the life in your years. Always do what you are afraid to do.",
  "You have brains in your head and feet in your shoes. You can steer yourself any direction you choose. You are on your own and you know what you know.",
  "The only impossible journey is the one you never begin. What lies behind you and what lies in front of you pales in comparison to what lies inside of you.",
  "Be yourself; everyone else is already taken. You only live once, but if you do it right, once is enough. Two things are infinite: the universe and human stupidity.",
  "A room without books is like a body without a soul. I am so clever that sometimes I do not understand a single word of what I am saying. Be the change you wish to see in the world.",
  "To live is the rarest thing in the world. Most people exist, that is all. I can resist everything except temptation. The truth is rarely pure and never simple.",
  "Darkness cannot drive out darkness; only light can do that. Hatred cannot drive out hatred; only love can do that. We must learn to live together as brothers or perish together as fools.",
  "The mind is not a vessel to be filled but a fire to be kindled. Do not go where the path may lead. Go instead where there is no path and leave a trail.",
  "We do not see things as they are. We see them as we are. You cannot shake hands with a clenched fist. Begin at the beginning and go on till you come to the end, then stop.",
  "Logic will get you from A to B. Imagination will take you everywhere. The only source of knowledge is experience. Science without religion is lame; religion without science is blind.",
  "Innovation distinguishes between a leader and a follower. Stay hungry, stay foolish. Your time is limited, so do not waste it living someone else's life.",
  "The secret of getting ahead is getting started. The secret of getting started is breaking your complex overwhelming tasks into small manageable tasks and then starting on the first one.",
  "Either you run the day or the day runs you. If you want to lift yourself up, lift up someone else. Do not wait; the time will never be just right.",

  // — Tongue twisters —
  "Peter Piper picked a peck of pickled peppers. A peck of pickled peppers Peter Piper picked. If Peter Piper picked a peck of pickled peppers, where is the peck of pickled peppers Peter Piper picked?",
  "She sells seashells by the seashore. The shells she sells are surely seashells. So if she sells shells on the seashore, I am sure she sells seashore shells.",
  "How much wood would a woodchuck chuck if a woodchuck could chuck wood? A woodchuck would chuck as much wood as a woodchuck could chuck if a woodchuck could chuck wood.",
  "Betty Botter bought some butter, but she said the butter is bitter. If I put it in my batter, it will make my batter bitter. So Betty Botter bought some better butter.",
  "I saw Susie sitting in a shoeshine shop. Where she sits she shines, and where she shines she sits. Six slippery snails slid slowly seaward. Fresh French fried fish, fresh fish fried fresh.",
  "The sixth sick sheikh's sixth sheep is sick. Red lorry, yellow lorry, red lorry, yellow lorry. Unique New York, unique New York, you know you need unique New York.",
  "How can a clam cram in a clean cream can? I wish to wish the wish you wish to wish, but if you wish the wish the witch wishes, you will not get the wish you wish to wish.",
  "Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy was not very fuzzy, was he? Whether the weather is warm, whether the weather is hot, we have to put up with the weather whether we like it or not.",
  "Can you can a can as a canner can can a can? I thought a thought, but the thought I thought was not the thought I thought I thought. If the thought I thought I thought had been the thought I thought, I would not have thought so much.",
  "Near an ear, a nearer ear, a nearly eerie ear. Twelve twins twirled twelve twigs. Pad kid poured curd pulled cod. Four fine fresh fish for you. Six slick slim slippery slender saplings.",

  // — Descriptive prose —
  "The old lighthouse stood at the edge of the cliff, its beam sweeping across the dark water in steady arcs. Fishermen far out at sea used it as their guide through stormy nights and thick fog.",
  "Rain tapped against the window in irregular rhythms as she sat by the fire, a cup of tea warming her hands. The cat had curled up on the armchair and was already fast asleep.",
  "Every morning the baker arrived before dawn to knead the dough and light the ovens. By seven the whole street smelled of warm bread and cinnamon rolls fresh from the rack.",
  "The train wound through the mountain pass with a low rumble, its windows framing snapshots of pine forests and snowcapped peaks before plunging into the darkness of a long tunnel.",
  "She had learned to read the weather by watching the clouds. Flat grey sheets meant steady rain. Tall white towers with dark bases meant storms were building somewhere over the hills.",
  "The market opened at first light when the farmers arrived with their trucks loaded with crates of vegetables, baskets of eggs, and bundles of fresh herbs tied with twine.",
  "He kept a small notebook in his jacket pocket and filled it with observations: the angle of light on an autumn afternoon, the exact sound a key makes in an old lock.",
  "The coral reef stretched for miles beneath the surface, a city of colour and motion. Parrotfish grazed on the coral while tiny cleaner shrimp waited at their stations.",
  "She had memorised every creak in the old farmhouse floor and could move through it in total darkness without making a sound, stepping first on the left side of the third stair.",
  "The village had one road in and one road out, and everyone knew when a stranger arrived because the baker's dog would bark and the sound would travel the full length of the street.",
  "Clouds gathered at the rim of the valley as if they were waiting for permission to enter. The air tasted of iron, the way it always did before a heavy summer thunderstorm.",
  "He repaired watches for a living, working in a small booth at the back of the market. His magnifying glass was always around his neck and his hands never seemed to tremble.",
  "The library was built in the year the town was founded and had never been closed, not during the flood, not during the war, and not during the long winter that followed.",
  "She typed at a speed that made her keyboard rattle. Her colleagues had learned to find the rhythm of it comforting, like rain on a roof or the ticking of a familiar clock.",
  "The submarine drifted at three hundred meters, its lights picking out a world that had never seen the sun. Strange pale creatures drifted past the portholes like living lanterns.",
  "Before the invention of clocks, people told time by the position of the sun and the length of shadows. Church bells divided the day into hours and called people to their prayers.",
  "He grew up by the river and learned to read it the way other children learned to read books. He could tell the depth by the colour, and the speed by the pattern of ripples.",
  "The competition was held every spring and drew competitors from three counties. Each team brought their best recipe and argued fiercely about the correct ratio of spice to sweetness.",
  "She had been a cartographer for thirty years and had drawn maps of places most people would never visit. She kept a worn copy of every map she had ever made in a leather trunk.",
  "The signal was weak but steady, a pulse of data crossing thousands of miles of ocean cable, carrying with it the words of a message that had been composed and revised over many weeks.",
  "There is a particular quality to light in late October, when the days are short and the sun stays low in the sky. It turns everything gold, even the most ordinary street corners.",
  "The robot had been programmed to sort packages but had developed an unexpected behaviour: it paused for three seconds at the window each morning and turned toward the rising sun.",
  "Mountains are patient. They do not hurry into shape or apologise for the space they occupy. They simply stand, accumulating weather, offering themselves to those willing to climb.",
  "The password had been changed twice that morning and no one had written it down. By afternoon the entire third floor was locked out and the IT desk had stopped answering its phone.",
  "She pressed her palm against the cold glass and watched the city below move in its usual morning patterns. Somewhere in that grid of streets her sister was also watching the same sky.",
  "The recipe called for patience above all other ingredients. The dough had to rest overnight, the sauce had to simmer for three hours, and the final dish had to cool before serving.",
  "Ancient traders carried spices wrapped in cloth across the desert, trading them for silver at the markets of great cities. A single bag of pepper was worth more than a horse.",
  "The orchestra tuned for several minutes, filling the hall with a pleasant dissonance that slowly resolved into silence. Then the conductor raised the baton and everything began.",
  "He had been told the building was haunted and believed it completely, even though the rational part of his mind knew the sounds were only pipes, the cold drafts only gaps in old plaster.",
  "Every letter she sent was written by hand on blue paper and sealed with wax. She believed that the effort of handwriting gave weight to words that a typed message could never have.",
  "The chess match had lasted six hours. Both players had been offered water three times and sandwiches twice. Neither had touched anything. Their focus was total and almost frightening.",
  "Scientists discovered that the trees in old forests were connected underground by a network of fungal threads. They share sugar and send chemical warnings when insects attack.",
  "The stadium held fifty thousand people but she only ever noticed the goalkeeper at the far end, standing alone, waiting, hands on knees, staring at the ball across the pitch.",
  "He wrote the first chapter seventeen times before he was satisfied with the opening sentence. The rest of the book took three months. The first chapter had taken nearly a year.",
  "The old printing press had produced a million pages in its lifetime. It smelled of ink and oil and the particular warmth of metal that has been heated and cooled a thousand times.",
  "She could identify any bird by its call alone. Standing in the dark garden at five in the morning she named them one by one: thrush, wren, blackbird, robin, and last of all a cuckoo.",
  "The fog came in overnight and stayed for three days. Ships anchored in the harbour and waited. Flights were cancelled. The town became briefly an island, cut off from everywhere else.",
  "He practiced the same piano piece every evening for a year. His neighbors never complained. They had come to think of it as part of the texture of the building, like the lift or the boiler.",
  "The jungle had swallowed the temple completely. Tree roots wrapped the stone columns like slow hands, and a fine green moss covered every carved surface, blurring all the details.",
  "She had not planned to run a marathon but found herself signed up after a moment of optimism in January. By April she was running six days a week and had bought her third pair of shoes.",
  "The telescope was pointed at a star that had ceased to exist before the first humans stood upright. Its light had been travelling for so long that the star itself was long gone.",
  "He ran the corner store for forty years and knew the first name of every regular customer and the middle name of most of their children. He never once forgot a birthday or a debt.",
  "The envelope had been sealed and addressed and left on the desk for six years. Whatever she had written inside had seemed important at the time but now she was afraid to reopen it.",
  "Water takes the shape of whatever contains it. People often do the same, fitting themselves to the shape of the room or the relationship or the expectation placed upon them.",
  "She had an extraordinary memory for numbers but forgot faces almost instantly. She could recall every phone number she had ever dialled but not the face of the person who answered.",
  "The expedition set out in good weather with three weeks of supplies and a plan that everyone privately doubted. They reached their goal on day nineteen and turned back immediately.",
  "The recipe had been passed down through four generations without ever being written down. Each person who received it changed one thing and told no one what the change had been.",
  "The city had grown up around the factory and could not imagine itself without it. When the factory closed, everyone in the city felt the absence like a missing tooth.",
  "He painted only at night, working by the light of a single lamp. He said daylight showed him what was there while night showed him what could be there, which was more interesting.",
  "The bridge had been built to last three hundred years. Engineers from all over the region came to study it because nothing about the design should have worked, and yet it held.",
  "She learned to swim at the age of forty-two, in a pool that smelled of chlorine and old rubber, surrounded by children half her height who moved through the water like small fish.",
  "The message in the bottle had been thrown from a ship in the middle of the Atlantic and was found on a beach in Portugal fourteen months later. The message said only: hello.",
  "He kept six clocks in his workshop, each set to a different time zone. He liked knowing what time it was in other places and imagining what those people might be doing right now.",
  "The hive had been in the old oak for twenty years. The beekeeper who tended it had inherited it from her grandmother and expected that someone would one day inherit it from her.",
  "The documentary had taken three years to film and followed a family of elephants across twelve hundred miles of savanna. The editor spent eight months making it into ninety minutes.",
  "She had memorised the periodic table as a child and still found comfort in its order. When she felt anxious she would recite the elements in sequence, starting always with hydrogen.",
  "The chess clock ticked. He had three minutes left and the position was losing. He sat back in his chair, closed his eyes for ten seconds, and then found the only move that saved the game.",
  "There is a kind of knowledge you can only learn by doing it wrong many times first. No book can teach you how to land a fish or talk to a stranger or lead a team through a crisis.",
  "The island appeared on no modern maps because it had been deliberately left off. The people who lived there had asked for privacy generations ago and that request had been honoured.",
  "She built model ships inside glass bottles, using long tweezers and a great deal of patience. Each one took about six weeks and she had made over two hundred in the past decade.",
  "The avalanche had buried the road under twelve meters of snow. The village on the other side would wait until spring, as it had waited before, as it would wait again.",
  "He had eaten at the same table in the same restaurant every Thursday for thirty years. The staff knew his order before he arrived and had his coffee ready when he sat down.",
  "The storm knocked out power to the whole district for eleven hours. People lit candles and talked to their neighbours and stayed up later than they usually did.",
  "She could not explain why certain combinations of notes made her feel as though she had forgotten something important. Music did that to her sometimes, reached into a gap she did not know she had.",
  "The glacier moved three centimeters per day, which was fast for a glacier. Scientists measured it every season and had recorded its steady retreat over the past forty years.",
  "He had been a lighthouse keeper for twelve years and had guided hundreds of ships safely past the rocks. He had never once spoken to any of the sailors whose lives he had saved.",
  "The computer took twenty minutes to boot up every morning. She used that time to write longhand in a small green notebook, a habit she had kept since before computers existed.",
  "The desert at night was colder than anyone who had not slept there could imagine. The stars were extraordinarily bright and numerous, and the silence had a particular texture to it.",
  "He had trained for the competition for two years, running twice a day, six days a week. He came fourth. He was back in training the following Monday.",
  "The letters arrived in bundles, tied with different coloured string, sorted by the decade in which they had been written. She read them in order, from the oldest to the most recent.",
  "The pond was exactly the right size for skating and froze reliably every winter. The children of the neighbourhood had been learning to skate on it for four generations.",
  "She translated books from Portuguese into English and from English into Portuguese. She said the second language always showed her something new about the first.",
  "The map had been drawn in 1742 and showed roads that no longer existed and rivers that had since changed course. And yet it was accurate in the ways that mattered most.",
  "The cat walked across the keyboard while she was on an important call. The resulting sequence of characters was accidentally sent to her entire contact list.",
  "He had collected stamps for fifty years without really understanding why. Now he was eighty and looking at the collection he had made, he thought he understood: he had wanted proof that places existed.",
  "The harbour seal hauled out on the same rock every morning and was gone by afternoon. Locals had given it a name and checked for it the way they checked for the weather.",
  "She had an eidetic memory for text but a poor memory for faces, which made reading effortless and social situations confusing. She had made peace with both.",
  "The satellite orbited at an altitude of four hundred kilometres and had a clear view of every point on earth at least once per day. It carried no instruments, only a single camera.",
  "He had never learned to type properly and still used two fingers, but he typed at remarkable speed and with very few errors. Watching him work was both frustrating and impressive.",
  "The lighthouse beam swept across the bay once every five seconds. From the hill above the village, if you watched long enough, you could set your watch by it.",
  "She spoke seven languages fluently and a further four at a level she called conversational. She said the hardest was not any particular language but the silence between them.",
];

export function getPassage(index: number): string {
  return PASSAGES[index % PASSAGES.length];
}

export function getRandomPassageIndex(): number {
  return Math.floor(Math.random() * PASSAGES.length);
}
